### ISSUE TITLE
Can't initialize Fakeit

### ISSUE THREAD

**Issue by JohannesDev** [moove-it/fakeit#62]
As soon as I try to initialize Fakeit with any language, for example `Fakeit.initWithLocale(Locale.GERMAN)`, the app crashes. 

The exception I get:

> FATAL EXCEPTION: main
>                                                                         Process: xxx.yyy.zzz, PID: 2274
>                                                                         java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
>                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
>                                                                          Caused by: java.lang.reflect.InvocationTargetException
>                                                                             at java.lang.reflect.Method.invoke(Native Method)
>                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
>                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
>                                                                          Caused by: java.io.FileNotFoundException: library/src/main/assets/locales/de-DE.yml (No such file or directory)
>                                                                             at java.io.FileInputStream.open(Native Method)
>                                                                             at java.io.FileInputStream.<init>(FileInputStream.java:146)
>                                                                             at com.mooveit.library.Fakeit.getValues(Fakeit.kt:81)
>                                                                             at com.mooveit.library.Fakeit.<init>(Fakeit.kt:71)
>                                                                             at com.mooveit.library.Fakeit.<init>(Fakeit.kt:51)
>                                                                             at com.mooveit.library.Fakeit$Companion.fakeitInit(Fakeit.kt:236)
>                                                                             at com.mooveit.library.Fakeit$Companion.initWithLocale(Fakeit.kt:256)
>                                                                             at xxx.yyy.zzz.HomeFragment.onClick(HomeFragment.kt:63)
>                                                                             at android.view.View.performClick(View.java:5624)
>                                                                             at android.view.View$PerformClick.run(View.java:22441)
>                                                                             at android.os.Handler.handleCallback(Handler.java:751)
>                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                             at android.os.Looper.loop(Looper.java:154)
>                                                                             at android.app.ActivityThread.main(ActivityThread.java:6316)
>                                                                             at java.lang.reflect.Method.invoke(Native Method) 
>                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872) 
>                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
> 

The .yml files seem to be missing but I don't know how to fix this

**Comment by JohannesDev** [comment]
Updating the version to 0.7 seems to solve the problem

**Comment by FlorianObermayer** [comment]
With **0.7** (also `Fakeit.initWithLocale(Locale.GERMAN)` I see a different exception:

``` org.yaml.snakeyaml.error.YAMLException: java.io.IOException: PushbackInputStream is closed
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4731)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: org.yaml.snakeyaml.error.YAMLException: java.io.IOException: PushbackInputStream is closed
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:200)
        at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:381)
        at com.mooveit.library.Fakeit.getValues(Fakeit.kt:81)
        at com.mooveit.library.Fakeit.<init>(Fakeit.kt:71)
        at com.mooveit.library.Fakeit.<init>(Fakeit.kt:51)
        at com.mooveit.library.Fakeit$Companion.fakeitInit(Fakeit.kt:236)
        at com.mooveit.library.Fakeit$Companion.initWithLocale(Fakeit.kt:256)
```

**Comment by Tooto** [comment]
Same problem here. 
v 0.7
